### ISSUE TITLE
ATX PSU 5v Standby Pin

### ISSUE THREAD

**Issue by avluis** [ultimachine/RAMBo#33]
Since the change from 1.1 to 1.2, the logic is powered by 12v from the power supply right?
Are we able to cut a trace on 1.2 and newer to supply 5v standby power to be able to use an ATX PSU's 5v standby and PS_ON pin with the corresponding ON - OFF G-code?

**Comment by avluis** [comment]
After plenty of experimenting, I was able to figure out that I just need to supply 5V to one of the pins while the other is controlled by the firmware's M80 & M81 commands - just what I needed.
When looking at the RAMBo and the PS_ON header - the pin closer to the power supply input is the 5V pin.
A good way to test is to simply power the RAMBo as usual then send a few M80 & M81 commands while testing the open pin. You know you have the right pin when you see a ground signal.

Also, depending on the 5v power supply or just on the way your power supply is wired, you will need to have a diode on the 5v signal from your power supply.

**Comment by Tailslide** [comment]
Can someone please explain how to do this in more detail?  The 5V standby power goes to the pin closest to the power supply input and the PS_ON goes to the other pin?  Where does the diode go and which way?
